163
PrimitivesLane/Publications pull request #25
Opened 2021-09-05 14:53 UTC by winkybupt

163

2021-09-06 16:37 UTC, freeyao requested changes

2021-09-06 16:37 UTC, freeyao commented on bitcoinops_zh/2021-08-25-newsletter-zh.md
> +- [LN 流动性广告和双供资通道是否允许第三方购买的流动性（"边车通道"）？](https://bitcoin.stackexchange.com/a/107786) David A. Harding 指出，虽然目前不支持，但使用[流动性广告](https://bitcoinops.org/en/topics/liquidity-advertisements/)和[双供资](https://b
双供资->双边供资

2021-09-07 00:40 UTC, winkybupt commented on bitcoinops_zh/2021-08-25-newsletter-zh.md
> +- **零基础费用 LN 讨论**：在LN协议中，花费者可以选择向每个帮助成功将付款路由到最终目的地的节点支付多少钱。反过来，路由节点可以选择拒绝任何没有为他们提供足够费用的付款尝试。为了使这种机制发挥作用，路由节点需要告知花费者他们期望的费用。[BOLT7] (https://github.com/lightningnetwork/lightning-rfc/blob/master/07-ro
嗯嗯，固定费用感觉更好点。财务里面也有固定成本、固定费用一说

2021-09-07 00:40 UTC, winkybupt commented on bitcoinops_zh/2021-08-25-newsletter-zh.md
> +  - **更多的分路，更多的费用**：比较用单路径支付和分成两条路径支付相同金额的方式：它们都将支付相同金额的总比例费用（因为总支付金额相同），但双路径支付将支付两倍的总基础费用（因为它使用两倍的跳数）。如果使用 `x` 个支付金额相同的路径进行支付，基本费用会高达 `x` 倍。这使得使用多路径支付更加昂贵，因此也不利于使用多路径支付的技术的发展。
统一改成固定费用

2021-09-07 02:43 UTC, merged