#164
PrimitivesLane/Publications pull request #27
Opened 2021-09-12 08:27 UTC by winkybupt

2021-09-13 10:45 UTC, freeyao requested changes
少数建议。
附 LN RFC 
https://github.com/lightningnetwork/lightning-rfc/blob/master/00-introduction.md

2021-09-13 10:45 UTC, freeyao commented on bitcoinops_zh/2021-09-01-newsletter-zh.md
> +- 在多路径支付中，*有更多*的不相关因素。多条路径不会有很强的时间锁和支付金额相关性。如果 LN 成功，其中会有足够多的时间相关性不强的付款。
不同的路径的时间锁及支付金额相关性不强，且若 LN 成功，其中会有足够多的时间相关性不强的付款。

2021-09-13 10:45 UTC, freeyao commented on bitcoinops_zh/2021-09-01-newsletter-zh.md
> +提升基础层和 LN 层之间的不相关性的一个方案是[不公开通道](https://bitcoinops.org/en/topics/unannounced-channels/)—— LN 上不会广播这些通道的存在。
非公开通道？下同。

2021-09-13 10:45 UTC, freeyao commented on bitcoinops_zh/2021-09-01-newsletter-zh.md
> +这种（相当小的）隐私提升也有助于公开的通道。已公开的通道只有在打开的时候才会被广播，所以当有人试图寻找已公开的通道时，不能找到*历史*通道。如果监视者想看到每一个已公开的通道，它必须自己存储所有这些数据，无法依赖任何一种"档案 "节点。
存档 节点？

2021-09-13 10:45 UTC, freeyao commented on bitcoinops_zh/2021-09-01-newsletter-zh.md
> +从理论上讲，实际的存款交易的输出点只有使用该通道的两个节点关注，网络上的其他节点不会关心任何两个节点之间的通道的安全问题。然而，公开的通道是通过 LN gossip 网络共享的。当一个节点收到一个传输过来的公开通道时，它会咨询自己信任的比特币全节点，检查存款输出点处是否存在，以及更重要的是检查**地址是否正确**。检查地址有助于确保通道传播机制难于被滥用；你需要区块链上存有资金，才能发送通道信息
检查地址有助于确保无法滥用通道传播机制

2021-09-14 15:06 UTC, winkybupt commented on bitcoinops_zh/2021-09-01-newsletter-zh.md
> +### LN 上的 PTLC
okok啊

2021-09-15 12:39 UTC, merged