#173
PrimitivesLane/Publications pull request #36
Opened 2021-11-09 16:07 UTC by winkybupt

2021-11-10 16:17 UTC, freeyao requested changes

2021-11-10 16:17 UTC, freeyao commented on bitcoinops_zh/2021-11-03-newsletter-zh.md
> +Optech 预计 taproot 的激活会顺利进行，但我们鼓励交易所和任何接受 709,632 区块附近大额交易的人升级他们的节点，或者准备在有任何问题迹象时暂时提高他们的确认限额。
出现 问题迹象？

2021-11-10 16:17 UTC, freeyao commented on bitcoinops_zh/2021-11-03-newsletter-zh.md
> +Optech 预计 taproot 的激活会顺利进行，但我们鼓励交易所和任何接受 709,632 区块附近大额交易的人升级他们的节点，或者准备在有任何问题迹象时暂时提高他们的确认限额。
confirmation limit 应该是指确认块数

2021-11-11 16:16 UTC, winkybupt commented on bitcoinops_zh/2021-11-03-newsletter-zh.md
> +虽然不太可能，但理论上还是有可能出现暂时的分叉。使用 [ForkMonitor.info][] 等服务或使用比特币核心中的 `getchaintips` RPC，应该可以监测到它。如果它真的发生了，轻量级客户可能会收到错误的确认信息。虽然理论上有可能得到 6 个确认，就像 2015 年的分叉一样，这将意味着矿工损失将近 250 万美元（2015 年的损失约为 5 万美元）。我们希望，在价值如此巨
哈哈哈，多么谦卑

2021-11-11 16:58 UTC, freeyao reviewed
#173

2021-11-11 16:58 UTC, merged